############# Navegação Português ##############

# main menu
[[main]]
name = "Início"
url = "/"
weight = 1

[[main]]
name = "Blog"
url = "/blog"
weight = 2

[[main]]
name = "Categorias"
url = "/categories"
weight = 3

[[main]]
name = "Sobre"
url = "/about"
weight = 4