############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"

[[main]]
name = "Blog"
url = "/blog"

[[main]]
name = "Categories"
url = "/categories"

[[main]]
name = "About"
url = "/about"


[[main]]
name = "Contact"
url = "/contact"

