############# Navegação Português ##############

# main menu
[[main]]
name = "Início"
url = "/"
weight = 1

[[main]]
name = "Blog"
url = "/blog"

[[main]]
name = "Categorias"
url = "/categories"

[[main]]
name = "Sobre"
url = "/about"

[[main]]
name = "Contato"
url = "/contact"